/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade02.view;

/**
 *
 * @author Arkins
 */
public class Genio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Genio.class.getName());

    /**
     * Creates new form Genio
     */
    public Genio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genio = new javax.swing.JLabel();
        jSpinnerValores = new javax.swing.JSpinner();
        valor = new javax.swing.JLabel();
        btnPalpite = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoBalao = new javax.swing.JTextArea();
        balao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        genio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade02/images/genio.png"))); // NOI18N
        getContentPane().add(genio);
        genio.setBounds(342, 162, 200, 200);

        jSpinnerValores.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(jSpinnerValores);
        jSpinnerValores.setBounds(101, 162, 100, 22);

        valor.setText("Valor");
        getContentPane().add(valor);
        valor.setBounds(62, 165, 27, 16);

        btnPalpite.setText("Palpite");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPalpite);
        btnPalpite.setBounds(101, 190, 72, 23);

        textoBalao.setColumns(20);
        textoBalao.setRows(5);
        textoBalao.setText("Vou pensar num numero entre 1 a 5\ntente adivinhar");
        jScrollPane2.setViewportView(textoBalao);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(250, 10, 240, 90);

        balao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade02/images/balao.png"))); // NOI18N
        getContentPane().add(balao);
        balao.setBounds(220, 0, 320, 160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        // TODO add your handling code here:
        /*
        primeiro crio um numero aleatorio que é o que o genio está 'pensando'
        então recebo o valor do spinner como string, e converto em int
        então comparo o numero do spinner com o gerado aleatoriamente
        */
        int numeroRand = 1 + (int)(5 * Math.random());
        String stringSpin = jSpinnerValores.getValue().toString();
        int numeroSpin = Integer.parseInt(stringSpin); 
        if (numeroRand == numeroSpin) {
            textoBalao.setText("Voce Acertou!");
        }else{
            textoBalao.setText("Voce Errou, o valor que eu pensei foi " + numeroRand);
            }
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Genio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balao;
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel genio;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerValores;
    private javax.swing.JTextArea textoBalao;
    private javax.swing.JLabel valor;
    // End of variables declaration//GEN-END:variables
}
