/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade01.view;

/**
 *
 * @author Arkins
 */
import javax.swing.JOptionPane;
public class CalculadoraIdade extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraIdade.class.getName());

    /**
     * Creates new form CalculadoraIdade
     */
    public CalculadoraIdade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anoNasc = new javax.swing.JLabel();
        campoMes = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        idade = new javax.swing.JLabel();
        campoRes = new javax.swing.JTextField();
        silhueta = new javax.swing.JLabel();
        mesNasc = new javax.swing.JLabel();
        diaNasc = new javax.swing.JLabel();
        campoDia = new javax.swing.JTextField();
        campoAno = new javax.swing.JTextField();
        imagemData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        anoNasc.setText("Ano de Nascimento");

        campoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMesActionPerformed(evt);
            }
        });

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade01/images/calculadora.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        idade.setText("Idade");

        campoRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoResActionPerformed(evt);
            }
        });

        silhueta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade01/images/silhueta.png"))); // NOI18N

        mesNasc.setText("Mês de Nascimento");

        diaNasc.setText("Dia de Nascimento");

        campoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDiaActionPerformed(evt);
            }
        });

        campoAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAnoActionPerformed(evt);
            }
        });

        imagemData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade01/images/data.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCalcular)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(idade)
                            .addGap(18, 18, 18)
                            .addComponent(campoRes)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(diaNasc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mesNasc)
                            .addComponent(anoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imagemData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(silhueta)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(diaNasc)
                                .addComponent(campoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mesNasc)
                                .addComponent(campoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(13, 13, 13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(anoNasc)
                                .addComponent(campoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(silhueta))
                    .addComponent(imagemData))
                .addGap(38, 38, 38)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idade)
                    .addComponent(campoRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMesActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
     /*
        pego o ano de nascimento escrito no campo ano da interface grafica, transformo em int. faço a mesma coisa com dia e mes.
        então recebo a data atual do sistema para uma idade mais precisa.
        
        */
        java.time.LocalDate dataAtual = java.time.LocalDate.now();
        int diaNascimento = Integer.parseInt(campoDia.getText()); 
        int mesNascimento = Integer.parseInt(campoMes.getText()); 
        int anoNascimento = Integer.parseInt(campoAno.getText()); 
        int anoAtual = dataAtual.getYear();
        int mesAtual = dataAtual.getMonthValue();
        int diaAtual = dataAtual.getDayOfYear();
        /*
        utilizo 3 ifs para possibilidades onde o usuario escreve opções erradas que possivelmente gerarão erros, mostrando a mensagem de erro na tela e pedindo para reinserir as informações
        
        */
        if(diaNascimento > 31 || diaNascimento < 1){
            JOptionPane.showMessageDialog(this,"Dia inválido, insira novamente um dia entre 1 e 31","Erro",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(mesNascimento > 12 || mesNascimento < 1){
            JOptionPane.showMessageDialog(this,"Mês inválido, insira novamente um mês entre 1 e 12","Erro",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(anoNascimento > anoAtual || anoNascimento < 1900){
            JOptionPane.showMessageDialog(this,"Ano inválido, insira novamente","Erro",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int idade = anoAtual - anoNascimento;//calculo da idade
        if(mesAtual < mesNascimento || (mesAtual == mesNascimento && diaAtual < diaNascimento)){
            idade--;
        }//faço um teste para ver se o aniversario já aconteceu ou não
        campoRes.setText("Idade: "+ idade + "Anos"); //mostro no campo de idade a idade da pessoa
      
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void campoResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoResActionPerformed

    private void campoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDiaActionPerformed

    private void campoAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraIdade().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anoNasc;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JTextField campoAno;
    private javax.swing.JTextField campoDia;
    private javax.swing.JTextField campoMes;
    private javax.swing.JTextField campoRes;
    private javax.swing.JLabel diaNasc;
    private javax.swing.JLabel idade;
    private javax.swing.JLabel imagemData;
    private javax.swing.JLabel mesNasc;
    private javax.swing.JLabel silhueta;
    // End of variables declaration//GEN-END:variables
}
